name: Run tests on pull requests

on:
  pull_request:
    branches: [main]

jobs:
  pr-test:
    runs-on: ubuntu-latest
    name: Testing PR
    steps:
      # setup
      - name: Checkout latest version
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.5.1
      - name: Install backend dependencies
        run: poetry install
      - name: Setup NodeJS v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install frontend dependencies
        run: npm install

      # backend checks
      - name: Run linter and type checker tests
        run: poetry run isort . --check &&
          poetry run black . --check &&
          poetry run mypy &&
          poetry run pflake8
      - name: Run unit tests with coverage check
        run: |
          poetry run coverage run -m pytest tests -vv &&
          poetry run coverage report
      - name: Validate that JSON schema is up-to-date
        run: poetry run python scripts/models/pydantic2jsonschema.py --check

      # frontend checks
      - name: Check Prettier formatting
        run: npx prettier --check frontend
      - name: Run Svelte check
        run: npm run check
      - name: Validate that Typescript data model is up-to-date
        run: node scripts/models/jsonschema2ts.mjs --check
